server:
  address: 'tcp://:9091'
  endpoints:
    authz:
      forward-auth:
        implementation: 'ForwardAuth'

log:
  level: info

theme: auto

totp:
  issuer: Blueprint
  algorithm: sha1
  digits: 6
  period: 30
  skew: 1

authentication_backend:
  password_reset:
    disable: false
  refresh_interval: 5m
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 65536
      parallelism: 8

access_control:
  default_policy: one_factor
  rules:
    - domain: auth.localhost
      policy: bypass

session:
  cookies:
    - name: authelia_session
      domain: auth.localhost
      authelia_url: https://auth.localhost
      expiration: 1h
      inactivity: 5m
      remember_me: 1M

regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m

storage:
  postgres:
    address: tcp://blueprint-postgres-authelia:5432

notifier:
  disable_startup_check: false
